export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    //<html lang="en">
      //<body>
      <div>
        {children}
      </div>
      //</body>
    //</html>
  )
}

// had to modify auto generated file, probably a bad idea
